-- StudentStay (MVP) - Supabase Postgres schema
-- Apply this in Supabase SQL Editor (or via migrations).

-- Extensions
create extension if not exists "pgcrypto";

-- Enums (as CHECK constraints to keep it simple for PostgREST)

-- Universities
create table if not exists public.universities (
  id smallint generated by default as identity primary key,
  name text not null unique
);

-- Profiles (1:1 with auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('student','landlord','admin')),
  email text not null,
  full_name text,

  -- student fields
  university_id smallint references public.universities(id),
  budget_min integer check (budget_min is null or budget_min >= 0),
  budget_max integer check (budget_max is null or budget_max >= 0),
  move_in_date date,

  -- landlord fields
  phone text,
  verification_status text check (verification_status is null or verification_status in ('pending','approved','rejected','suspended')),
  verified_at timestamptz,

  -- admin/user mgmt
  account_status text not null default 'active' check (account_status in ('active','suspended','banned')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Admin-only notes about landlord verification decisions
create table if not exists public.landlord_verification_notes (
  landlord_id uuid primary key references public.profiles(id) on delete cascade,
  notes text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Listings (public fields only; private address is in listing_private)
create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  landlord_id uuid not null references public.profiles(id) on delete cascade,

  title text not null,
  city text not null default 'Dublin' check (city = 'Dublin'),
  university_id smallint not null references public.universities(id),

  rent_monthly_eur integer not null check (rent_monthly_eur > 0),
  deposit_eur integer not null check (deposit_eur >= 0),
  bills_included boolean not null default false,

  room_type text not null check (room_type in ('single_room','shared_room','entire_property')),
  available_from date not null,
  min_stay text not null check (min_stay in ('short_term','semester','academic_year')),

  description text not null,
  house_rules text,

  status text not null default 'draft' check (status in ('draft','pending_review','active','under_offer','let','deactivated')),
  moderation_notes text,

  -- denormalized for public badge (avoids exposing profile fields)
  landlord_verified boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.listing_private (
  listing_id uuid primary key references public.listings(id) on delete cascade,
  address text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.listing_photos (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  storage_path text not null,
  sort_order smallint not null check (sort_order >= 1 and sort_order <= 6),
  created_at timestamptz not null default now(),
  unique (listing_id, sort_order)
);

create table if not exists public.enquiries (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  move_in_date date,
  length_of_stay text,
  message text not null,
  status text not null default 'open' check (status in ('open','closed')),
  created_at timestamptz not null default now()
);

create table if not exists public.enquiry_messages (
  id uuid primary key default gen_random_uuid(),
  enquiry_id uuid not null references public.enquiries(id) on delete cascade,
  sender_role text not null check (sender_role in ('student','landlord','admin')),
  sender_id uuid not null references public.profiles(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.landlord_verification_docs (
  id uuid primary key default gen_random_uuid(),
  landlord_id uuid not null references public.profiles(id) on delete cascade,
  doc_type text not null check (doc_type in ('government_id','proof_of_ownership')),
  storage_path text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.listing_reports (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  reason text not null check (reason in ('asked_for_money_upfront','suspicious_communication','fake_photos','too_good_to_be_true','other')),
  details text,
  status text not null default 'open' check (status in ('open','resolved')),
  resolved_at timestamptz,
  resolved_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigserial primary key,
  actor_id uuid references public.profiles(id),
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Indexes (search + queues)
create index if not exists idx_listings_status on public.listings(status);
create index if not exists idx_listings_university on public.listings(university_id);
create index if not exists idx_listings_rent on public.listings(rent_monthly_eur);
create index if not exists idx_listings_available_from on public.listings(available_from);
create index if not exists idx_listings_room_type on public.listings(room_type);
create index if not exists idx_listings_min_stay on public.listings(min_stay);
create index if not exists idx_listings_created_at on public.listings(created_at desc);

create index if not exists idx_enquiries_student on public.enquiries(student_id, created_at desc);
create index if not exists idx_enquiries_listing on public.enquiries(listing_id, created_at desc);
create index if not exists idx_reports_status on public.listing_reports(status, created_at desc);
create index if not exists idx_profiles_role on public.profiles(role);
create index if not exists idx_profiles_verification_status on public.profiles(verification_status);

-- updated_at trigger helper
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_listings_updated_at on public.listings;
create trigger trg_listings_updated_at
before update on public.listings
for each row execute function public.set_updated_at();

drop trigger if exists trg_listing_private_updated_at on public.listing_private;
create trigger trg_listing_private_updated_at
before update on public.listing_private
for each row execute function public.set_updated_at();

drop trigger if exists trg_landlord_verification_notes_updated_at on public.landlord_verification_notes;
create trigger trg_landlord_verification_notes_updated_at
before update on public.landlord_verification_notes
for each row execute function public.set_updated_at();

-- Enforce: max 6 photos per listing
create or replace function public.enforce_listing_photo_limit()
returns trigger
language plpgsql
as $$
declare
  c integer;
begin
  select count(*) into c from public.listing_photos where listing_id = new.listing_id;
  if c >= 6 then
    raise exception 'photo_limit_exceeded';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_photo_limit on public.listing_photos;
create trigger trg_photo_limit
before insert on public.listing_photos
for each row execute function public.enforce_listing_photo_limit();

-- Enforce: max 5 enquiries/day per student
create or replace function public.enforce_daily_enquiry_limit()
returns trigger
language plpgsql
as $$
declare
  c integer;
  day_start timestamptz := date_trunc('day', now());
  day_end timestamptz := date_trunc('day', now()) + interval '1 day';
begin
  select count(*) into c
  from public.enquiries
  where student_id = new.student_id
    and created_at >= day_start
    and created_at < day_end;

  if c >= 5 then
    raise exception 'daily_limit_exceeded';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enquiry_rate_limit on public.enquiries;
create trigger trg_enquiry_rate_limit
before insert on public.enquiries
for each row execute function public.enforce_daily_enquiry_limit();

-- Enforce: max 5 reports/day per student
create or replace function public.enforce_daily_report_limit()
returns trigger
language plpgsql
as $$
declare
  c integer;
  day_start timestamptz := date_trunc('day', now());
  day_end timestamptz := date_trunc('day', now()) + interval '1 day';
begin
  select count(*) into c
  from public.listing_reports
  where student_id = new.student_id
    and created_at >= day_start
    and created_at < day_end;

  if c >= 5 then
    raise exception 'daily_limit_exceeded';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_report_rate_limit on public.listing_reports;
create trigger trg_report_rate_limit
before insert on public.listing_reports
for each row execute function public.enforce_daily_report_limit();

-- Keep listings.landlord_verified in sync with profiles.verification_status
create or replace function public.sync_landlord_verified_to_listings()
returns trigger
language plpgsql
as $$
begin
  if new.role = 'landlord' then
    update public.listings
      set landlord_verified = (new.verification_status = 'approved')
    where landlord_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_sync_landlord_verified on public.profiles;
create trigger trg_sync_landlord_verified
after update of verification_status on public.profiles
for each row execute function public.sync_landlord_verified_to_listings();

create or replace function public.set_listing_landlord_verified_on_insert()
returns trigger
language plpgsql
as $$
declare
  vs text;
begin
  select verification_status into vs from public.profiles where id = new.landlord_id;
  new.landlord_verified = (vs = 'approved');
  return new;
end;
$$;

drop trigger if exists trg_set_listing_landlord_verified on public.listings;
create trigger trg_set_listing_landlord_verified
before insert on public.listings
for each row execute function public.set_listing_landlord_verified_on_insert();

-- Listing status transition guards (MVP)
create or replace function public.guard_listing_status()
returns trigger
language plpgsql
as $$
declare
  is_admin boolean;
  landlord_status text;
begin
  -- Determine admin by profiles table (RLS-safe: this runs inside DB with current JWT)
  select (auth.role() = 'service_role') or exists(
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.account_status = 'active'
  ) into is_admin;

  if new.status = 'active' and not is_admin then
    raise exception 'only_admin_can_activate';
  end if;

  if new.status = 'pending_review' then
    select verification_status into landlord_status
    from public.profiles p
    where p.id = new.landlord_id;

    if landlord_status is distinct from 'approved' then
      raise exception 'landlord_not_verified';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_guard_listing_status on public.listings;
create trigger trg_guard_listing_status
before insert or update of status on public.listings
for each row execute function public.guard_listing_status();

